version: '3.8'

services:
  prometheus:
    image: prom/prometheus
    container_name: nanolambda-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  prophet:
    build: ./prophet
    container_name: nanolambda-prophet
    environment:
      - PROMETHEUS_URL=http://prometheus:9090
      - GATEWAY_URL=http://host.docker.internal:8080
    depends_on:
      - prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"
